DROP TABLE IF EXISTS list CASCADE;
DROP TABLE IF EXISTS task CASCADE;
DROP TABLE IF EXISTS background CASCADE;

CREATE TABLE list (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255)
);

CREATE TABLE task (
  id SERIAL PRIMARY KEY NOT NULL,
  content VARCHAR(255),
  list_id INTEGER REFERENCES list(id) ON DELETE CASCADE
);

CREATE TABLE background (
  id SERIAL PRIMARY KEY NOT NULL,
  url VARCHAR(255)
);
